const demoUsers={
  'ceo@triobyte.com':{password:'Demo@123',role:'CEO',name:'Founder / CEO',initials:'C',level:'Founder'},
  'hr@triobyte.com':{password:'Demo@123',role:'HR',name:'HR Manager',initials:'H',level:'Management'},
  'admin@triobyte.com':{password:'Demo@123',role:'Admin',name:'System Administrator',initials:'A',level:'Administrator'},
  'emp001@triobyte.com':{password:'Demo@123',role:'Employee',name:'Parth Patel',initials:'P',level:'L3'}
};

const menus={
  CEO:[['dashboard','Dashboard','⌂'],['overview','Company Overview','▦'],['analytics','Analytics','◌'],['projects','Projects','▣'],['teams','Teams','♙'],['employees','Employees','♧'],['attendance','Attendance','◷'],['finance','Finance','₹'],['repositories','Repositories','⌘'],['tasks','Tasks','✓'],['reports','Reports','▤'],['messages','Messages','☵']],
  HR:[['dashboard','Dashboard','⌂'],['employees','Employees','♙'],['interns','Interns','◇'],['attendance','Attendance','◷'],['leave','Leave Management','✓'],['tasks','Tasks & Deadlines','▣'],['performance','Performance','↗'],['salary','Salary','₹'],['overtime','Overtime','◴'],['roles','Role Management','♧'],['worklog','Work Logs','▤'],['reports','Reports','▥'],['messages','Messages','☵']],
  Admin:[['dashboard','Dashboard','⌂'],['users','Users','♙'],['roles','Roles & Permissions','♧'],['tasks','Tasks & Deadlines','✓'],['projects','Projects','▣'],['repositories','Repositories','⌘'],['monitoring','System Monitoring','◉'],['announcements','Announcements','◇'],['backup','Backup & Restore','↻'],['audit','Audit Logs','▤'],['reports','Reports','▥']],
  Employee:[['dashboard','Dashboard','⌂'],['tasks','My Tasks','✓'],['projects','My Projects','▣'],['repositories','Code Repositories','⌘'],['worklog','Work Log','▤'],['attendance','Attendance','◷'],['leave','Leave','✓'],['chat','Chats','☵'],['groups','Groups','♧'],['documents','Documents','▤'],['certificates','Certificates','▧'],['profile','Profile','♙']]
};

let currentUser=null;
let currentPage='dashboard';
const $=s=>document.querySelector(s);
const pageContent=$('#pageContent');

function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}
function esc(value){return String(value).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]))}
function setTheme(theme){document.body.classList.remove('dark','accent');if(theme==='dark')document.body.classList.add('dark');if(theme==='accent')document.body.classList.add('accent');localStorage.setItem('triobyteTheme',theme);document.querySelectorAll('.theme-btn').forEach(b=>b.classList.toggle('active',b.dataset.theme===theme))}
function loadTheme(){setTheme(localStorage.getItem('triobyteTheme')||'light')}

function buildNav(){const nav=$('#navMenu');nav.innerHTML=menus[currentUser.role].map(([page,label,icon])=>`<button class="nav-item ${page===currentPage?'active':''}" data-page="${page}"><span>${icon}</span>${label}</button>`).join('')}
function updateUser(){
  $('#sidebarRole').textContent=currentUser.role.toUpperCase();
  $('#userName').textContent=currentUser.name;
  $('#userRole').textContent=`${currentUser.role} • ${currentUser.level}`;
  $('#userAvatar').textContent=currentUser.initials;
}
function openApp(){
  $('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');
  buildNav();updateUser();loadTheme();renderPage(currentPage);
}
function logout(){currentUser=null;localStorage.removeItem('triobyteUser');$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden');$('#loginForm').reset();toast('Signed out safely.')}
function login(email,password){
  const user=demoUsers[email.toLowerCase()];
  if(!user||user.password!==password){toast('Invalid company email or password.');return}
  currentUser={...user,email:email.toLowerCase()};localStorage.setItem('triobyteUser',JSON.stringify(currentUser));openApp();toast(`Welcome back, ${user.name}.`)
}

function stat(icon,label,value,foot,kind='blue'){return `<article class="stat-card"><div class="stat-top"><span class="stat-label">${label}</span><span class="stat-icon ${kind}">${icon}</span></div><div class="stat-value">${value}</div><div class="stat-foot">${foot}</div></article>`}
function panel(title,body,extra=''){return `<section class="panel ${extra}"><div class="panel-title"><h3>${title}</h3>${body.includes('View All')?'': '<small>Updated today</small>'}</div>${body}</section>`}
function listRows(items){return `<div class="list">${items.map(x=>`<div class="list-row"><div><strong>${x[0]}</strong><small>${x[1]}</small></div><span class="badge ${x[3]||''}">${x[2]}</span></div>`).join('')}</div>`}
function chart(){return `<div class="chart">${[55,68,62,78,70,88,80,96].map(h=>`<i style="--h:${h}%"></i>`).join('')}</div><div class="chart-labels"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div>`}
function ring(total='128'){return `<div class="ring-wrap"><div class="ring"><div class="ring-center">${total}</div></div><div class="legend"><span><i class="dot" style="background:var(--blue)"></i>Development 68</span><span><i class="dot" style="background:var(--green)"></i>Design 24</span><span><i class="dot" style="background:var(--orange)"></i>Sales 16</span><span><i class="dot" style="background:#cbd3de"></i>Other 20</span></div></div>`}
function progressRows(items){return `<div class="list">${items.map(x=>`<div class="list-row"><div style="flex:1"><strong>${x[0]}</strong><small>${x[1]}</small><div class="progress"><i style="--w:${x[2]}%"></i></div></div><span class="badge ${x[3]||'blue'}">${x[2]}%</span></div>`).join('')}</div>`}

function dashboardCEO(){return `<div class="page-head"><div><div class="welcome">Good morning, ${esc(currentUser.name)} 👋</div><h1>Executive overview</h1><p>Company-wide performance, people, projects and operations.</p></div><span class="badge blue">Monday, 20 Aug 2026</span></div><div class="stats-grid">${stat('♙','Total Employees','128','+12% vs last month','blue')}${stat('▣','Active Projects','32','+8% vs last month','green')}${stat('₹','Revenue This Month','₹48.75L','+15.3% vs last month','orange')}${stat('▤','Open Risks','4','2 require attention','red')}</div><div class="dashboard-grid">${panel('Company performance',chart(),'span-2')}${panel('Project status',ring('32'))}${panel('Top departments',progressRows([['Development','Delivery health',92],['Design','Delivery health',85],['Sales','Target progress',78],['HR','Operations',90]]))}${panel('Recent alerts',listRows([['Project AI Chatbot delayed','High priority','Action','red'],['5 employees on leave','People operations','Review','orange'],['Open merge requests','Engineering','27','blue']]))}${panel('Management activity',listRows([['New project created','Mobile Banking App','2h ago','green'],['Salary processed','Finance cycle','Today','blue'],['Employee promoted','Level change','Yesterday','purple']]))}</div>`}

function dashboardHR(){return `<div class="page-head"><div><div class="welcome">Good morning, ${esc(currentUser.name)} 👋</div><h1>People operations</h1><p>Manage employees, attendance, leave and workforce activity.</p></div><span class="badge blue">HR workspace</span></div><div class="stats-grid">${stat('♙','Total Employees','128','+5 this month','purple')}${stat('●','Present Today','98','76% of total','green')}${stat('◷','On Leave Today','18','14% of total','orange')}${stat('◇','New Joiners','7','This month','blue')}</div><div class="dashboard-grid">${panel('Attendance overview',chart(),'span-2')}${panel('Employee distribution',ring())}${panel('Leave requests',listRows([['Aman Tiwari','15 Jun – 17 Jun','Pending','orange'],['Neha Iyer','24 Jun – 25 Jun','Pending','orange'],['Vikram Patel','20 Jun','Approved','green'],['Kavya Nair','18 Jun – 20 Jun','Rejected','red']]))}${panel('Upcoming birthdays',listRows([['Rohan Verma','Frontend Developer','24 Jun','blue'],['Neha Iyer','UI/UX Designer','26 Jun','blue'],['Kavya Nair','HR Executive','28 Jun','blue']]))}${panel('HR tasks',listRows([['Review leave requests','6 pending','Open','orange'],['Interview scheduled','3 today','Today','blue'],['Documents to verify','4 pending','Open','orange'],['Onboarding tasks','2 pending','Open','green']]))}</div>`}

function dashboardAdmin(){return `<div class="page-head"><div><div class="welcome">System overview, ${esc(currentUser.name)}</div><h1>Administration</h1><p>Users, permissions, security, system activity and operational controls.</p></div><span class="badge green">Systems healthy</span></div><div class="stats-grid">${stat('♙','Total Users','132','+10% vs last month','blue')}${stat('●','Active Sessions','118','89% of total','green')}${stat('◉','System Uptime','99.9%','This month','green')}${stat('!','Pending Requests','8','Require action','red')}</div><div class="dashboard-grid">${panel('User role distribution',ring('132'))}${panel('System activity',chart())}${panel('Security overview',listRows([['Failed logins','Last 7 days','12','red'],['Password changes','Last 7 days','24','blue'],['Blocked users','Current','3','orange'],['Open audit alerts','Requires review','2','red']]))}${panel('Recent system logs',`<div class="table-wrap"><table class="table"><thead><tr><th>Event</th><th>User</th><th>Time</th></tr></thead><tbody><tr><td>User login</td><td>emp001@triobyte.com</td><td>10:20 AM</td></tr><tr><td>Role updated</td><td>hr@triobyte.com</td><td>09:15 AM</td></tr><tr><td>New user created</td><td>admin@triobyte.com</td><td>08:44 AM</td></tr><tr><td>Password reset</td><td>emp014@triobyte.com</td><td>08:20 AM</td></tr></tbody></table></div>`,'span-2')}</div>`}

function dashboardEmployee(){return `<div class="page-head"><div><div class="welcome">Good morning, ${esc(currentUser.name)} 👋</div><h1>Your work summary</h1><p>Everything you need for today's work, projects and company activity.</p></div><span class="badge blue">Employee • ${esc(currentUser.level)}</span></div><div class="stats-grid">${stat('✓','My Tasks','12','5 due today','blue')}${stat('▣','My Projects','3','2 in progress','green')}${stat('◷','Active Project Deadline','28 Jun','5 days left','orange')}${stat('▤',"Today's Work Log",'6h 30m','Logged today','purple')}</div><div class="dashboard-grid">${panel('Active project',`<div><strong>AI Chatbot System</strong><p style="color:var(--muted);font-size:11px;line-height:1.5">Internal customer-support automation project assigned to you.</p><div class="progress"><i style="--w:75%"></i></div><div style="display:flex;justify-content:space-between;margin-top:8px;font-size:10px;color:var(--muted)"><span>75% complete</span><span>Due 28 Jun 2026</span></div></div>`,'span-2')}${panel("Today's work log",listRows([['Implemented login API','2h 00m','Done','green'],['Integrated chatbot module','2h 15m','Done','green'],['Fixed UI bug','1h 00m','Done','green'],['Code review','1h 15m','Done','green']]))}${panel('Attendance calendar',`<div class="table-wrap"><table class="table"><thead><tr><th>Mon</th><th>Tue</th><th>Wed</th><th>Thu</th><th>Fri</th></tr></thead><tbody><tr><td>18 ✓</td><td>19 ✓</td><td>20 ✓</td><td>21 ✓</td><td>22 ✓</td></tr><tr><td>25 ✓</td><td>26 ✓</td><td>27 •</td><td>28</td><td>29</td></tr></tbody></table></div>`)}${panel('My projects',progressRows([['AI Chatbot System','In Progress',75],['Mobile Banking App','In Progress',60],['Website Redesign','On Hold',30,'orange']]))}${panel('Upcoming tasks',listRows([['Fix login API issue','AI Chatbot System','Due today','red'],['Create dashboard UI','Admin Portal','Tomorrow','orange'],['Review code PR #245','Mobile Banking App','In 2 days','blue'],['Update documentation','Internal Project','In 3 days','green']]))}</div>`}

function genericPage(title,subtitle,body){return `<div class="page-head"><div><div class="welcome">${esc(currentUser.role)} workspace</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><button class="primary-btn" data-action="demo">+ New</button></div>${body}`}
function pageFor(role,page){
  if(page==='dashboard')return role==='CEO'?dashboardCEO():role==='HR'?dashboardHR():role==='Admin'?dashboardAdmin():dashboardEmployee();
  if(page==='profile')return genericPage('My profile','Your company identity and employment information.',`<div class="profile"><section class="panel profile-card"><div class="profile-avatar">${currentUser.initials}</div><h3>${esc(currentUser.name)}</h3><p>${esc(currentUser.role)} • ${esc(currentUser.level)}</p><span class="badge green">Active employee</span></section><section class="panel"><div class="form-grid"><label>Full Name<input value="${esc(currentUser.name)}"></label><label>Company Email<input value="${esc(currentUser.email)}" readonly></label><label>Employee ID<input value="EMP001"></label><label>Company ID<input value="TRI-EMP-001"></label><label>Mobile Number<input placeholder="+91 ..."></label><label>Joining Date<input value="20 Apr 2026"></label><label>Employment status<input value="Permanent"></label><label>Employee level<input value="${esc(currentUser.level)}"></label><label class="full">Address<textarea rows="3" placeholder="Company record address"></textarea></label><button class="primary-btn">Save changes</button></div></section></div>`);
  if(page==='settings')return genericPage('Settings','Control your appearance, password and account preferences.',`<div class="settings-grid"><button class="theme-btn ${!document.body.classList.contains('dark')&&!document.body.classList.contains('accent')?'active':''}" data-theme="light"><div class="theme-preview"></div><strong>Light</strong><small>Clean company workspace</small></button><button class="theme-btn ${document.body.classList.contains('dark')?'active':''}" data-theme="dark"><div class="theme-preview dark"></div><strong>Dark</strong><small>Low-light workspace</small></button><button class="theme-btn ${document.body.classList.contains('accent')?'active':''}" data-theme="accent"><div class="theme-preview accent"></div><strong>Custom Accent</strong><small>Triobyte accent experience</small></button></div><div class="panel" style="margin-top:14px"><div class="panel-title"><h3>Security</h3></div><button class="primary-btn" data-action="password">Change password</button></div>`);
  if(page==='tasks'||page==='projects'||page==='repositories'||page==='employees'||page==='users'||page==='interns'||page==='attendance'||page==='leave'||page==='salary'||page==='overtime'||page==='roles'||page==='worklog'||page==='reports'||page==='messages'||page==='chat'||page==='groups'||page==='documents'||page==='certificates'||page==='analytics'||page==='overview'||page==='teams'||page==='finance'||page==='monitoring'||page==='announcements'||page==='backup'||page==='audit'||page==='performance')return modulePage(page);
  return genericPage('Coming module','This screen is part of the portal foundation and will be connected to the backend in the next implementation stage.',`<section class="panel"><h3>Ready for backend integration</h3><p style="color:var(--muted);line-height:1.6">The navigation, responsive shell, role separation and design tokens are in place. Data, permissions and server actions must be implemented before this is production-ready.</p></section>`);
}
function modulePage(page){
 const names={tasks:'Tasks & Deadlines',projects:'Projects',repositories:'Code Repositories',employees:'Employees',users:'Users',interns:'Intern Management',attendance:'Attendance',leave:'Leave Management',salary:'Salary Tracking',overtime:'Overtime Tracking',roles:'Roles & Permissions',worklog:'Work Logs',reports:'Reports',messages:'Messages',chat:'Chats',groups:'Groups',documents:'Documents',certificates:'Certificates',analytics:'Analytics',overview:'Company Overview',teams:'Teams',finance:'Finance',monitoring:'System Monitoring',announcements:'Announcements',backup:'Backup & Restore',audit:'Audit Logs',performance:'Performance'};
 const title=names[page]||'Portal module';
 let rows=[['AI Chatbot System','Parth Patel','In Progress','75%'],['Mobile Banking App','Aman Tiwari','In Progress','60%'],['Website Redesign','Neha Iyer','On Hold','30%'],['Internal CRM','Kavya Nair','Completed','100%']];
 if(page==='attendance')rows=[['Parth Patel','Present','20 Aug 2026','6h 30m'],['Aman Tiwari','Present','20 Aug 2026','7h 10m'],['Neha Iyer','Leave','20 Aug 2026','—'],['Kavya Nair','Present','20 Aug 2026','8h 02m']];
 if(page==='leave')rows=[['Aman Tiwari','Casual Leave','15–17 Jun','Pending'],['Neha Iyer','Sick Leave','24–25 Jun','Pending'],['Vikram Patel','Casual Leave','20 Jun','Approved'],['Kavya Nair','Work From Home','18 Jun','Rejected']];
 if(page==='employees'||page==='users'||page==='interns')rows=[['Parth Patel','EMP001','Frontend Developer','Active'],['Aman Tiwari','EMP002','Backend Developer','Active'],['Neha Iyer','EMP003','UI/UX Designer','On Leave'],['Kavya Nair','EMP004','HR Executive','Active']];
 return genericPage(title,`Manage ${title.toLowerCase()} from the ${currentUser.role} workspace.`,`<section class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Owner / Type</th><th>Status / Date</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}<td><button class="link-btn" data-action="demo">View</button></td></tr>`).join('')}</tbody></table></div></section>`)
}
function renderPage(page){currentPage=page;buildNav();pageContent.innerHTML=pageFor(currentUser.role,page);$('#sidebar').classList.remove('open');$('#sidebarOverlay').classList.remove('show');pageContent.querySelectorAll('[data-theme]').forEach(b=>b.addEventListener('click',()=>{setTheme(b.dataset.theme);renderPage('settings')}));pageContent.querySelectorAll('[data-action="demo"]').forEach(b=>b.addEventListener('click',()=>toast('UI action is ready; backend service will be connected in the next stage.')));pageContent.querySelectorAll('[data-action="password"]').forEach(b=>b.addEventListener('click',showPasswordModal))}
function showPasswordModal(){showModal(`<h2 id="modalTitle">Change password</h2><p>For production, this form will be validated server-side and stored using secure password hashing.</p><div class="form-stack"><label>Current password<input type="password"></label><label>New password<input type="password" minlength="12"></label><label>Confirm new password<input type="password" minlength="12"></label><button class="primary-btn" data-action="demo">Update password</button></div>`)}
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');$('#modalContent').querySelectorAll('[data-action="demo"]').forEach(b=>b.addEventListener('click',()=>{toast('Password workflow is ready for secure backend integration.');$('#modal').classList.add('hidden')}))}

$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login($('#loginEmail').value.trim(),$('#loginPassword').value)})
$('#forgotBtn').addEventListener('click',()=>showModal(`<h2 id="modalTitle">Forgot password</h2><p>Password reset will be handled through the company identity service. No public account creation is available.</p><button class="primary-btn" data-action="demo">Request reset</button>`))
$('#closeModal').addEventListener('click',()=>$('#modal').classList.add('hidden'))
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')})
$('#navMenu').addEventListener('click',e=>{const btn=e.target.closest('[data-page]');if(btn)renderPage(btn.dataset.page)})
$('#pageContent').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)renderPage(b.dataset.page)})
$('#openSidebar').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#sidebarOverlay').classList.add('show')})
$('#closeSidebar').addEventListener('click',()=>{$('#sidebar').classList.remove('open');$('#sidebarOverlay').classList.remove('show')})
$('#sidebarOverlay').addEventListener('click',()=>{$('#sidebar').classList.remove('open');$('#sidebarOverlay').classList.remove('show')})
$('#logoutBtn').addEventListener('click',logout);$('#sidebarLogout').addEventListener('click',logout)
$('#notificationBtn').addEventListener('click',()=>showModal(`<h2 id="modalTitle">Notifications</h2>${listRows([['Project deadline approaching','AI Chatbot System','5 days','orange'],['Leave request pending','HR approval required','Action','red'],['New company announcement','Townhall meeting','2h ago','blue']])}`))
$('#messageBtn').addEventListener('click',()=>{const p=currentUser.role==='Employee'?'chat':'messages';renderPage(p)})
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim();if(q)toast(`Search queued for “${q}”.`)}})

window.addEventListener('storage',()=>loadTheme())
const saved=localStorage.getItem('triobyteUser');if(saved){try{currentUser=JSON.parse(saved);if(currentUser&&menus[currentUser.role])openApp()}catch{localStorage.removeItem('triobyteUser')}}

/* Frontend preview credentials — remove these before production deployment. */
window.TriobyteDemoAccounts=Object.keys(demoUsers).map(email=>({email,password:demoUsers[email].password,role:demoUsers[email].role}));
